[
new Item("Rock", "https://rainworld.miraheze.org/wiki/Rock", "https://static.wikitide.net/rainworldwiki/f/ff/Rock_icon.png", []),
new Item("Flashbang", "https://rainworld.miraheze.org/wiki/Flashbang", "https://static.wikitide.net/rainworldwiki/9/92/Flashbang_icon.png", []),
new Item("Vulture Mask", "https://rainworld.miraheze.org/wiki/Vulture_Mask", "https://static.wikitide.net/rainworldwiki/9/95/Vulture_Mask_icon.png", []),
new Item("Spore Puff", "https://rainworld.miraheze.org/wiki/Spore_Puff", "https://static.wikitide.net/rainworldwiki/4/40/Spore_Puff_icon.png", []),
new Item("Lantern", "https://rainworld.miraheze.org/wiki/Lantern", "https://static.wikitide.net/rainworldwiki/4/46/Lantern_icon.png", []),
new Item("Mushroom", "https://rainworld.miraheze.org/wiki/Mushroom", "https://static.wikitide.net/rainworldwiki/a/a8/Mushroom_icon.png", []),
new Item("Cherrybomb", "https://rainworld.miraheze.org/wiki/Cherrybomb", "https://static.wikitide.net/rainworldwiki/1/1e/Cherrybomb_icon.png", []),
new Item("Batnip", "https://rainworld.miraheze.org/wiki/Batnip", "https://static.wikitide.net/rainworldwiki/1/15/Batnip_icon.png", []),
new Item("Grenade", "https://rainworld.miraheze.org/wiki/Grenade", "https://static.wikitide.net/rainworldwiki/5/5e/Grenade_icon.png", []),
new Item("Beehive", "https://rainworld.miraheze.org/wiki/Beehive", "https://static.wikitide.net/rainworldwiki/6/6c/Beehive_icon.png", []),
new Item("Bubble Weed", "https://rainworld.miraheze.org/wiki/Bubble_Weed", "https://static.wikitide.net/rainworldwiki/5/59/Bubble_Weed_icon.png", []),
new Item("Noodlefly Egg", "https://rainworld.miraheze.org/wiki/Noodlefly_Egg", "https://static.wikitide.net/rainworldwiki/e/e1/Noodlefly_Egg_icon.png", []),
new Item("Karma Flower", "https://rainworld.miraheze.org/wiki/Karma_Flower", "https://static.wikitide.net/rainworldwiki/7/75/Karma_Flower_icon.png", []),
new Item("Singularity Bomb", "https://rainworld.miraheze.org/wiki/Singularity_Bomb", "https://static.wikitide.net/rainworldwiki/6/67/Singularity_Bomb_icon.png", []),
new Item("Overseer Eye", "https://rainworld.miraheze.org/wiki/Overseer_Eye", "https://static.wikitide.net/rainworldwiki/4/4f/Overseer_Eye_icon.png", []),
new Item("Pearl", "https://rainworld.miraheze.org/wiki/Pearl", "https://static.wikitide.net/rainworldwiki/0/09/Pearl_Misc.png", []),
new Item("Neuron Fly", "https://rainworld.miraheze.org/wiki/Neuron_Fly", "https://static.wikitide.net/rainworldwiki/2/2a/Neuron_Fly_icon.png", []),
new Item("Fire Egg", "https://rainworld.miraheze.org/wiki/Fire_Egg", "https://static.wikitide.net/rainworldwiki/b/b9/Fire_Egg_icon.png", []),
new Item("Blue Fruit", "https://rainworld.miraheze.org/wiki/Blue_Fruit", "https://static.wikitide.net/rainworldwiki/9/95/Blue_Fruit_icon.png", []),
new Item("Bubble Fruit", "https://rainworld.miraheze.org/wiki/Bubble_Fruit", "https://static.wikitide.net/rainworldwiki/6/62/Bubble_Fruit_icon.png", []),
new Item("Slime Mold", "https://rainworld.miraheze.org/wiki/Slime_Mold", "https://static.wikitide.net/rainworldwiki/7/7e/Slime_Mold_icon.png", []),
new Item("Jellyfish", "https://rainworld.miraheze.org/wiki/Jellyfish", "https://static.wikitide.net/rainworldwiki/b/b0/Jellyfish_icon.png", []),
new Item("Eggbug Egg", "https://rainworld.miraheze.org/wiki/Eggbug_Egg", "https://static.wikitide.net/rainworldwiki/8/8a/Eggbug_Egg_icon.png", []),
new Item("Seed", "https://rainworld.miraheze.org/wiki/Seed", "https://static.wikitide.net/rainworldwiki/c/c6/Seed_icon.png", []),
new Item("Gooieduck", "https://rainworld.miraheze.org/wiki/Gooieduck", "https://static.wikitide.net/rainworldwiki/d/dd/Gooieduck_icon.png", []),
new Item("Lilypuck", "https://rainworld.miraheze.org/wiki/Lilypuck", "https://static.wikitide.net/rainworldwiki/6/6a/Lilypuck_icon.png", []),
new Item("Glow Weed", "https://rainworld.miraheze.org/wiki/Glow_Weed", "https://static.wikitide.net/rainworldwiki/8/8a/Glow_Weed_icon.png", []),
new Item("Dandelion Peach", "https://rainworld.miraheze.org/wiki/Dandelion_Peach", "https://static.wikitide.net/rainworldwiki/8/80/Dandelion_Peach_icon.png", []),
new Item("Batfly", "https://rainworld.miraheze.org/wiki/Batfly", "https://static.wikitide.net/rainworldwiki/9/90/Batfly_icon.png", []),
new Item("Infant Centipede", "https://rainworld.miraheze.org/wiki/Infant_Centipede", "https://static.wikitide.net/rainworldwiki/b/ba/Infant_Centipede_icon.png", []),
new Item("Vulture Grub", "https://rainworld.miraheze.org/wiki/Vulture_Grub", "https://static.wikitide.net/rainworldwiki/3/3b/Vulture_Grub_icon.png", []),
new Item("Infant Noodlefly", "https://rainworld.miraheze.org/wiki/Infant_Noodlefly", "https://static.wikitide.net/rainworldwiki/5/50/Infant_Noodlefly_icon.png", []),
new Item("Hazer", "https://rainworld.miraheze.org/wiki/Hazer", "https://static.wikitide.net/rainworldwiki/3/32/Hazer_icon.png", []),
new Item("Snail", "https://rainworld.miraheze.org/wiki/Snail", "https://static.wikitide.net/rainworldwiki/1/1d/Snail_icon.png", []),
new Item("Grappling Worm", "https://rainworld.miraheze.org/wiki/Grappling_Worm", "https://static.wikitide.net/rainworldwiki/4/4d/Grappling_Worm_icon.png", []),
new Item("Food", "https://rainworld.miraheze.org/wiki/Food", "https://static.wikitide.net/rainworldwiki/5/54/Food_pip_full_%28medium%29.png", [])
]