
//Define some global scope variables

function setupCrafts(){
    selItem = null
    available = []
    mode = "ItemInfo"

    new Item("Rock", "https://rainworld.miraheze.org/wiki/Rock", "https://static.wikitide.net/rainworldwiki/f/ff/Rock_icon.png", ["Rubish", "Stone"])
    new Item("Flashbang", "https://rainworld.miraheze.org/wiki/Flashbang", "https://static.wikitide.net/rainworldwiki/9/92/Flashbang_icon.png", [])
    new Item("Vulture Mask", "https://rainworld.miraheze.org/wiki/Vulture_Mask", "https://static.wikitide.net/rainworldwiki/9/95/Vulture_Mask_icon.png", [])
    new Item("Spore Puff", "https://rainworld.miraheze.org/wiki/Spore_Puff", "https://static.wikitide.net/rainworldwiki/4/40/Spore_Puff_icon.png", [])
    new Item("Lantern", "https://rainworld.miraheze.org/wiki/Lantern", "https://static.wikitide.net/rainworldwiki/4/46/Lantern_icon.png", [])
    new Item("Mushroom", "https://rainworld.miraheze.org/wiki/Mushroom", "https://static.wikitide.net/rainworldwiki/a/a8/Mushroom_icon.png", [])
    new Item("Cherrybomb", "https://rainworld.miraheze.org/wiki/Cherrybomb", "https://static.wikitide.net/rainworldwiki/1/1e/Cherrybomb_icon.png", [])
    new Item("Batnip", "https://rainworld.miraheze.org/wiki/Batnip", "https://static.wikitide.net/rainworldwiki/1/15/Batnip_icon.png", [])
    new Item("Grenade", "https://rainworld.miraheze.org/wiki/Grenade", "https://static.wikitide.net/rainworldwiki/5/5e/Grenade_icon.png", [])
    new Item("Beehive", "https://rainworld.miraheze.org/wiki/Beehive", "https://static.wikitide.net/rainworldwiki/6/6c/Beehive_icon.png", ["Paincone"])
    new Item("Bubble Weed", "https://rainworld.miraheze.org/wiki/Bubble_Weed", "https://static.wikitide.net/rainworldwiki/5/59/Bubble_Weed_icon.png", [])
    new Item("Noodlefly Egg", "https://rainworld.miraheze.org/wiki/Noodlefly_Egg", "https://static.wikitide.net/rainworldwiki/e/e1/Noodlefly_Egg_icon.png", [])
    new Item("Karma Flower", "https://rainworld.miraheze.org/wiki/Karma_Flower", "https://static.wikitide.net/rainworldwiki/7/75/Karma_Flower_icon.png", [])
    new Item("Singularity Bomb", "https://rainworld.miraheze.org/wiki/Singularity_Bomb", "https://static.wikitide.net/rainworldwiki/6/67/Singularity_Bomb_icon.png", [])
    new Item("Overseer Eye", "https://rainworld.miraheze.org/wiki/Overseer_Eye", "https://static.wikitide.net/rainworldwiki/4/4f/Overseer_Eye_icon.png", [])
    new Item("Pearl", "https://rainworld.miraheze.org/wiki/Pearl", "https://static.wikitide.net/rainworldwiki/0/09/Pearl_Misc.png", [])
    new Item("Neuron Fly", "https://rainworld.miraheze.org/wiki/Neuron_Fly", "https://static.wikitide.net/rainworldwiki/2/2a/Neuron_Fly_icon.png", [])
    new Item("Fire Egg", "https://rainworld.miraheze.org/wiki/Fire_Egg", "https://static.wikitide.net/rainworldwiki/b/b9/Fire_Egg_icon.png", [])
    new Item("Blue Fruit", "https://rainworld.miraheze.org/wiki/Blue_Fruit", "https://static.wikitide.net/rainworldwiki/9/95/Blue_Fruit_icon.png", [])
    new Item("Bubble Fruit", "https://rainworld.miraheze.org/wiki/Bubble_Fruit", "https://static.wikitide.net/rainworldwiki/6/62/Bubble_Fruit_icon.png", [])
    new Item("Slime Mold", "https://rainworld.miraheze.org/wiki/Slime_Mold", "https://static.wikitide.net/rainworldwiki/7/7e/Slime_Mold_icon.png", [])
    new Item("Jellyfish", "https://rainworld.miraheze.org/wiki/Jellyfish", "https://static.wikitide.net/rainworldwiki/b/b0/Jellyfish_icon.png", [])
    new Item("Eggbug Egg", "https://rainworld.miraheze.org/wiki/Eggbug_Egg", "https://static.wikitide.net/rainworldwiki/8/8a/Eggbug_Egg_icon.png", [])
    new Item("Seed", "https://rainworld.miraheze.org/wiki/Seed", "https://static.wikitide.net/rainworldwiki/c/c6/Seed_icon.png", [])
    new Item("Gooieduck", "https://rainworld.miraheze.org/wiki/Gooieduck", "https://static.wikitide.net/rainworldwiki/d/dd/Gooieduck_icon.png", [])
    new Item("Lilypuck", "https://rainworld.miraheze.org/wiki/Lilypuck", "https://static.wikitide.net/rainworldwiki/6/6a/Lilypuck_icon.png", [])
    new Item("Glow Weed", "https://rainworld.miraheze.org/wiki/Glow_Weed", "https://static.wikitide.net/rainworldwiki/8/8a/Glow_Weed_icon.png", [])
    new Item("Dandelion Peach", "https://rainworld.miraheze.org/wiki/Dandelion_Peach", "https://static.wikitide.net/rainworldwiki/8/80/Dandelion_Peach_icon.png", [])
    new Item("Batfly", "https://rainworld.miraheze.org/wiki/Batfly", "https://static.wikitide.net/rainworldwiki/9/90/Batfly_icon.png", [])
    new Item("Infant Centipede", "https://rainworld.miraheze.org/wiki/Infant_Centipede", "https://static.wikitide.net/rainworldwiki/b/ba/Infant_Centipede_icon.png", [])
    new Item("Vulture Grub", "https://rainworld.miraheze.org/wiki/Vulture_Grub", "https://static.wikitide.net/rainworldwiki/3/3b/Vulture_Grub_icon.png", [])
    new Item("Infant Noodlefly", "https://rainworld.miraheze.org/wiki/Infant_Noodlefly", "https://static.wikitide.net/rainworldwiki/5/50/Infant_Noodlefly_icon.png", [])
    new Item("Hazer", "https://rainworld.miraheze.org/wiki/Hazer", "https://static.wikitide.net/rainworldwiki/3/32/Hazer_icon.png", ["Ink Fish", "Squid"])
    new Item("Snail", "https://rainworld.miraheze.org/wiki/Snail", "https://static.wikitide.net/rainworldwiki/1/1d/Snail_icon.png", ["Saint Killer"])
    new Item("Grappling Worm", "https://rainworld.miraheze.org/wiki/Grappling_Worm", "https://static.wikitide.net/rainworldwiki/4/4d/Grappling_Worm_icon.png", ["Grapple Worm", "Wormithy"])
    new Item("Food", "https://rainworld.miraheze.org/wiki/Food", "https://static.wikitide.net/rainworldwiki/5/54/Food_pip_full_%28medium%29.png", ["Pips"])


    new Craft(Item.getItem("Rock"), Item.getItem("Flashbang"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Rock"), Item.getItem("Vulture Mask"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Rock"), Item.getItem("Spore Puff"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Rock"), Item.getItem("Lantern"), Item.getItem("Flashbang"))
    new Craft(Item.getItem("Rock"), Item.getItem("Mushroom"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Rock"), Item.getItem("Cherrybomb"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Rock"), Item.getItem("Batnip"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Rock"), Item.getItem("Grenade"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Rock"), Item.getItem("Beehive"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Rock"), Item.getItem("Bubble Weed"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Rock"), Item.getItem("Noodlefly Egg"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Rock"), Item.getItem("Karma Flower"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Rock"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Rock"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Rock"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Rock"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Rock"), Item.getItem("Blue Fruit"), Item.getItem("Flashbang"))
    new Craft(Item.getItem("Rock"), Item.getItem("Bubble Fruit"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Rock"), Item.getItem("Slime Mold"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Rock"), Item.getItem("Jellyfish"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Rock"), Item.getItem("Eggbug Egg"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Rock"), Item.getItem("Seed"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Rock"), Item.getItem("Gooieduck"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Rock"), Item.getItem("Lilypuck"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Rock"), Item.getItem("Glow Weed"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Rock"), Item.getItem("Dandelion Peach"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Rock"), Item.getItem("Batfly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Rock"), Item.getItem("Infant Centipede"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Rock"), Item.getItem("Vulture Grub"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Rock"), Item.getItem("Infant Noodlefly"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Rock"), Item.getItem("Hazer"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Vulture Mask"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Spore Puff"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Lantern"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Mushroom"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Cherrybomb"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Batnip"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Grenade"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Beehive"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Bubble Weed"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Noodlefly Egg"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Karma Flower"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Blue Fruit"), Item.getItem("Slime Mold"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Bubble Fruit"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Slime Mold"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Jellyfish"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Eggbug Egg"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Seed"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Gooieduck"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Lilypuck"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Glow Weed"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Dandelion Peach"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Batfly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Infant Centipede"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Vulture Grub"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Infant Noodlefly"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Flashbang"), Item.getItem("Hazer"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Spore Puff"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Lantern"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Mushroom"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Cherrybomb"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Batnip"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Grenade"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Beehive"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Bubble Weed"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Noodlefly Egg"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Karma Flower"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Blue Fruit"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Bubble Fruit"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Slime Mold"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Jellyfish"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Eggbug Egg"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Seed"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Gooieduck"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Lilypuck"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Glow Weed"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Dandelion Peach"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Batfly"), Item.getItem("Seed"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Infant Centipede"), Item.getItem("Seed"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Vulture Grub"), Item.getItem("Seed"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Infant Noodlefly"), Item.getItem("Seed"))
    new Craft(Item.getItem("Vulture Mask"), Item.getItem("Hazer"), Item.getItem("Seed"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Lantern"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Mushroom"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Cherrybomb"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Batnip"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Grenade"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Beehive"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Bubble Weed"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Noodlefly Egg"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Karma Flower"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Blue Fruit"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Bubble Fruit"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Slime Mold"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Jellyfish"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Eggbug Egg"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Seed"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Gooieduck"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Lilypuck"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Glow Weed"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Dandelion Peach"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Batfly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Infant Centipede"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Vulture Grub"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Infant Noodlefly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Spore Puff"), Item.getItem("Hazer"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Mushroom"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Cherrybomb"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Batnip"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Grenade"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Beehive"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Bubble Weed"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Noodlefly Egg"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Karma Flower"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Blue Fruit"), Item.getItem("Flashbang"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Bubble Fruit"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Slime Mold"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Jellyfish"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Eggbug Egg"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Seed"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Gooieduck"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Lilypuck"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Glow Weed"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Dandelion Peach"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Batfly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Infant Centipede"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Vulture Grub"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Infant Noodlefly"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Lantern"), Item.getItem("Hazer"), Item.getItem("Snail"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Cherrybomb"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Batnip"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Grenade"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Beehive"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Bubble Weed"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Noodlefly Egg"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Karma Flower"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Singularity Bomb"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Blue Fruit"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Bubble Fruit"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Slime Mold"), Item.getItem("Infant Noodlefly"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Jellyfish"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Eggbug Egg"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Seed"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Gooieduck"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Lilypuck"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Glow Weed"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Dandelion Peach"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Batfly"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Infant Centipede"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Vulture Grub"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Infant Noodlefly"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Mushroom"), Item.getItem("Hazer"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Batnip"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Grenade"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Beehive"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Bubble Weed"), Item.getItem("Snail"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Noodlefly Egg"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Karma Flower"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Blue Fruit"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Bubble Fruit"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Slime Mold"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Jellyfish"), Item.getItem("Batnip"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Eggbug Egg"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Seed"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Gooieduck"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Lilypuck"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Glow Weed"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Dandelion Peach"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Batfly"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Infant Centipede"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Vulture Grub"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Infant Noodlefly"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Cherrybomb"), Item.getItem("Hazer"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Grenade"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Beehive"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Bubble Weed"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Noodlefly Egg"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Karma Flower"), Item.getItem("Seed"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Blue Fruit"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Bubble Fruit"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Slime Mold"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Jellyfish"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Eggbug Egg"), Item.getItem("Gooieduck"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Seed"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Gooieduck"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Lilypuck"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Glow Weed"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Dandelion Peach"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Batfly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Infant Centipede"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Vulture Grub"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Infant Noodlefly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Batnip"), Item.getItem("Hazer"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Beehive"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Bubble Weed"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Noodlefly Egg"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Karma Flower"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Fire Egg"), Item.getItem("Singularity Bomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Blue Fruit"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Bubble Fruit"), Item.getItem("Snail"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Slime Mold"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Jellyfish"), Item.getItem("Snail"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Eggbug Egg"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Seed"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Gooieduck"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Lilypuck"), Item.getItem("Beehive"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Glow Weed"), Item.getItem("Lantern"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Dandelion Peach"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Batfly"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Infant Centipede"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Vulture Grub"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Infant Noodlefly"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Grenade"), Item.getItem("Hazer"), Item.getItem("Flashbang"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Bubble Weed"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Noodlefly Egg"), Item.getItem("Grappling Worm"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Karma Flower"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Blue Fruit"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Bubble Fruit"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Slime Mold"), Item.getItem("Cherrybomb"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Jellyfish"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Eggbug Egg"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Seed"), Item.getItem("Grappling Worm"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Gooieduck"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Lilypuck"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Glow Weed"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Dandelion Peach"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Batfly"), Item.getItem("Batnip"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Infant Centipede"), Item.getItem("Grappling Worm"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Vulture Grub"), Item.getItem("Flashbang"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Infant Noodlefly"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Beehive"), Item.getItem("Hazer"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Noodlefly Egg"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Karma Flower"), Item.getItem("Seed"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Fire Egg"), Item.getItem("Grenade"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Blue Fruit"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Bubble Fruit"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Slime Mold"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Jellyfish"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Eggbug Egg"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Seed"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Gooieduck"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Lilypuck"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Glow Weed"), Item.getItem("Lilypuck"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Dandelion Peach"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Batfly"), Item.getItem("Batnip"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Infant Centipede"), Item.getItem("Jellyfish"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Vulture Grub"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Infant Noodlefly"), Item.getItem("Mushroom"))
    new Craft(Item.getItem("Bubble Weed"), Item.getItem("Hazer"), Item.getItem("Glow Weed"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Karma Flower"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Singularity Bomb"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Fire Egg"), Item.getItem("Vulture Grub"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Blue Fruit"), Item.getItem("Batfly"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Bubble Fruit"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Slime Mold"), Item.getItem("Infant Centipede"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Jellyfish"), Item.getItem("Snail"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Eggbug Egg"), Item.getItem("Infant Noodlefly"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Seed"), Item.getItem("Infant Noodlefly"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Gooieduck"), Item.getItem("Grappling Worm"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Lilypuck"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Glow Weed"), Item.getItem("Hazer"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Dandelion Peach"), Item.getItem("Infant Noodlefly"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Batfly"), Item.getItem("Seed"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Infant Centipede"), Item.getItem("Seed"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Vulture Grub"), Item.getItem("Seed"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Infant Noodlefly"), Item.getItem("Seed"))
    new Craft(Item.getItem("Noodlefly Egg"), Item.getItem("Hazer"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Overseer Eye"), Item.getItem("Neuron Fly"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Fire Egg"), Item.getItem("Singularity Bomb"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Blue Fruit"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Bubble Fruit"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Slime Mold"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Jellyfish"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Eggbug Egg"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Seed"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Gooieduck"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Lilypuck"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Glow Weed"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Dandelion Peach"), Item.getItem("Seed"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Batfly"), Item.getItem("Batnip"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Infant Centipede"), Item.getItem("Spore Puff"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Vulture Grub"), Item.getItem("Vulture Mask"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Infant Noodlefly"), Item.getItem("Noodlefly Egg"))
    new Craft(Item.getItem("Karma Flower"), Item.getItem("Hazer"), Item.getItem("Bubble Weed"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Overseer Eye"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Fire Egg"), Item.getItem("Karma Flower"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Blue Fruit"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Bubble Fruit"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Slime Mold"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Jellyfish"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Eggbug Egg"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Seed"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Gooieduck"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Lilypuck"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Glow Weed"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Dandelion Peach"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Batfly"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Infant Centipede"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Vulture Grub"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Infant Noodlefly"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Singularity Bomb"), Item.getItem("Hazer"), Item.getItem("Fire Egg"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Neuron Fly"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Fire Egg"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Blue Fruit"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Bubble Fruit"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Slime Mold"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Jellyfish"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Eggbug Egg"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Seed"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Gooieduck"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Lilypuck"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Glow Weed"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Dandelion Peach"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Batfly"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Infant Centipede"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Vulture Grub"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Infant Noodlefly"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Overseer Eye"), Item.getItem("Hazer"), Item.getItem("Pearl"))
    new Craft(Item.getItem("Pearl"), Item.getItem("Neuron Fly"), Item.getItem("Overseer Eye"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Fire Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Blue Fruit"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Bubble Fruit"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Slime Mold"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Jellyfish"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Neuron Fly"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Blue Fruit"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Bubble Fruit"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Slime Mold"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Jellyfish"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Fire Egg"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Bubble Fruit"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Slime Mold"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Jellyfish"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Blue Fruit"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Slime Mold"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Jellyfish"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Bubble Fruit"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Jellyfish"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Slime Mold"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Eggbug Egg"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Jellyfish"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Seed"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Eggbug Egg"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Gooieduck"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Seed"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Lilypuck"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Gooieduck"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Glow Weed"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Lilypuck"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Dandelion Peach"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Glow Weed"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Dandelion Peach"), Item.getItem("Batfly"), Item.getItem("Food"))
    new Craft(Item.getItem("Dandelion Peach"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Dandelion Peach"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Dandelion Peach"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Dandelion Peach"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Batfly"), Item.getItem("Infant Centipede"), Item.getItem("Food"))
    new Craft(Item.getItem("Batfly"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Batfly"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Batfly"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Infant Centipede"), Item.getItem("Vulture Grub"), Item.getItem("Food"))
    new Craft(Item.getItem("Infant Centipede"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Infant Centipede"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Vulture Grub"), Item.getItem("Infant Noodlefly"), Item.getItem("Food"))
    new Craft(Item.getItem("Vulture Grub"), Item.getItem("Hazer"), Item.getItem("Food"))
    new Craft(Item.getItem("Infant Noodlefly"), Item.getItem("Hazer"), Item.getItem("Food"))
}